#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}GENOMES${NC} ############################"
echo -e "#################################################################"

## glycy
./gradlew integrate --stacktrace -Psource=G1267.gnm1.YWW6

## glyd3
./gradlew integrate --stacktrace -Psource=G1403.gnm1.CL6K

## glydo
./gradlew integrate --stacktrace -Psource=G1134.gnm1.PP7B

## glyfa
./gradlew integrate --stacktrace -Psource=G1718.gnm1.B1PY

## glyma
./gradlew integrate --stacktrace -Psource=FiskebyIII.gnm1.F177
./gradlew integrate --stacktrace -Psource=Hefeng25_IGA1002.gnm1.L69T
./gradlew integrate --stacktrace -Psource=Huaxia3_IGA1007.gnm1.RGGN
./gradlew integrate --stacktrace -Psource=Jinyuan_IGA1006.gnm1.LXM0
./gradlew integrate --stacktrace -Psource=Lee.gnm1.BXNC
./gradlew integrate --stacktrace -Psource=Lee.gnm2.K7BV
./gradlew integrate --stacktrace -Psource=Wenfeng7_IGA1001.gnm1.L0QH
./gradlew integrate --stacktrace -Psource=Wm82.gnm1.FCtY
./gradlew integrate --stacktrace -Psource=Wm82.gnm2.DTC4
./gradlew integrate --stacktrace -Psource=Wm82.gnm4.4PTR
./gradlew integrate --stacktrace -Psource=Wm82_IGA1008.gnm1.5CQQ
./gradlew integrate --stacktrace -Psource=Zh13.gnm1.N6C8
./gradlew integrate --stacktrace -Psource=Zh13.gnm2.LV9P
./gradlew integrate --stacktrace -Psource=Zh13_IGA1005.gnm1.FRXQ
./gradlew integrate --stacktrace -Psource=Zh35_IGA1004.gnm1.DBYJ

## glyst
./gradlew integrate --stacktrace -Psource=G1974.gnm1.7MZB

## glyso
./gradlew integrate --stacktrace -Psource=F_IGA1003.gnm1.V9RB
./gradlew integrate --stacktrace -Psource=PI483463.gnm1.YJWS
./gradlew integrate --stacktrace -Psource=W05.gnm1.SVL1

## glysy
./gradlew integrate --stacktrace -Psource=G1300.gnm1.C11H

