#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################### ${LP}ANNOTATION${NC} ##########################"
echo -e "#################################################################"

## glycy
./gradlew integrate --stacktrace -Psource=G1267.gnm1.ann1.HRFD

## glyd3
./gradlew integrate --stacktrace -Psource=G1403.gnm1.ann1.XNZQ

## glydo
./gradlew integrate --stacktrace -Psource=G1718.gnm1.ann1.2KSV

## glyma
./gradlew integrate --stacktrace -Psource=FiskebyIII.gnm1.ann1.SS25
./gradlew integrate --stacktrace -Psource=Hefeng25_IGA1002.gnm1.ann1.320V
./gradlew integrate --stacktrace -Psource=Huaxia3_IGA1007.gnm1.ann1.LKC7
./gradlew integrate --stacktrace -Psource=Jinyuan_IGA1006.gnm1.ann1.2NNX
./gradlew integrate --stacktrace -Psource=Lee.gnm1.ann1.6NZV
./gradlew integrate --stacktrace -Psource=Lee.gnm2.ann1.1FNT
./gradlew integrate --stacktrace -Psource=Wenfeng7_IGA1001.gnm1.ann1.ZK5W
# ./gradlew integrate --stacktrace -Psource=Wm82.gnm1.ann1.DvBy
# ./gradlew integrate --stacktrace -Psource=Wm82.gnm2.ann1.RVB6
# ./gradlew integrate --stacktrace -Psource=Wm82.gnm4.ann1.T8TQ
./gradlew integrate --stacktrace -Psource=Wm82_IGA1008.gnm1.ann1.FGN6
./gradlew integrate --stacktrace -Psource=Zh13.gnm1.ann1.8VV3
./gradlew integrate --stacktrace -Psource=Zh13.gnm2.ann1.FJ3G
./gradlew integrate --stacktrace -Psource=Zh13_IGA1005.gnm1.ann1.87Z5
./gradlew integrate --stacktrace -Psource=Zh35_IGA1004.gnm1.ann1.RGN6

## glyso
./gradlew integrate --stacktrace -Psource=F_IGA1003.gnm1.ann1.G61B
./gradlew integrate --stacktrace -Psource=PI483463.gnm1.ann1.3Q3Q
./gradlew integrate --stacktrace -Psource=W05.gnm1.ann1.T47J

## glyst
./gradlew integrate --stacktrace -Psource=G1974.gnm1.ann1.F257

## glysy
./gradlew integrate --stacktrace -Psource=G1300.gnm1.ann1.RRK6
