#!/bin/sh

rm -f *.log

echo ""
echo "######################################################################################################################"
echo "######################################################################################################################"
echo "################################################ INTEGRATE ###########################################################"
echo "######################################################################################################################"
echo "######################################################################################################################"
echo ""

## ontologies
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=soybean-ontology --stacktrace

## InterPro
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

###########
## glyma ##
###########

./gradlew integrate -Psource=glyma-about --stacktrace
./gradlew integrate -Psource=glyma-phenotypes --stacktrace

## glyma.mixed
./gradlew integrate -Psource=mixed.gwas.1W14-gwas --stacktrace

## glyma.Wm82.gnm2
./gradlew integrate -Psource=glyma.Wm82.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-expression --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.mrk1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1.syn1-synteny --stacktrace

## glyma.Lee.gnm1
./gradlew integrate -Psource=glyma.Lee.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-mrna-fasta --stacktrace

## glyma.Zh13.gnm1
./gradlew integrate -Psource=glyma.Zh13.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-protein-fasta --stacktrace

###########
## glyso ##
###########

./gradlew integrate -Psource=glyso-about --stacktrace

## glyso.PI483463.gnm1
./gradlew integrate -Psource=glyso.PI483463.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-mrna-fasta --stacktrace

## glyso.W05.gnm1
./gradlew integrate -Psource=glyso.W05.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-protein-fasta --stacktrace
