#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}DESCRIPTIONS${NC} #########################"
echo -e "#################################################################"

## Glycine
# ./gradlew integrate --stacktrace -Psource=glycy-description
# ./gradlew integrate --stacktrace -Psource=glyd3-description
# ./gradlew integrate --stacktrace -Psource=glydo-description
# ./gradlew integrate --stacktrace -Psource=glyfa-description
# ./gradlew integrate --stacktrace -Psource=glyma-description
# ./gradlew integrate --stacktrace -Psource=glyso-description
# ./gradlew integrate --stacktrace -Psource=glyst-description
# ./gradlew integrate --stacktrace -Psource=glysy-description


## others from synteny
./gradlew integrate --stacktrace -Psource=aradu-description
./gradlew integrate --stacktrace -Psource=araip-description
./gradlew integrate --stacktrace -Psource=cajca-description
./gradlew integrate --stacktrace -Psource=lotja-description
./gradlew integrate --stacktrace -Psource=lupan-description
./gradlew integrate --stacktrace -Psource=medtr-description
./gradlew integrate --stacktrace -Psource=phavu-description
./gradlew integrate --stacktrace -Psource=vigan-description
./gradlew integrate --stacktrace -Psource=vigra-description
