#!/bin/sh

echo ""
echo "######################################################################################################################"
echo "######################################################################################################################"
echo "############################################ SOYMINE INTEGRATE #######################################################"
echo "######################################################################################################################"
echo "######################################################################################################################"
echo ""

## ontologies
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=soybean-crop-ontology --stacktrace
./gradlew integrate -Psource=soybean-ontology --stacktrace

## InterPro
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families and trees
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace
./gradlew integrate -Psource=lis.fam1-phylotree --stacktrace

## about
./gradlew integrate -Psource=glyma-about --stacktrace
# ./gradlew integrate -Psource=glyso-about --stacktrace

## Wm82.gnm1
./gradlew integrate -Psource=glyma.Wm82.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-gfa --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.ann1-pathway --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm1.mrk --stacktrace


## Wm82.gnm2
./gradlew integrate -Psource=glyma.Wm82.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1.syn1-synteny --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-gfa --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-pathway --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.mrk --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.div.0SZD --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.div.47GQ --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.div.5KDR --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-expression --stacktrace


## Wm82.gnm4
# ./gradlew integrate -Psource=glyma.Wm82.gnm4-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-mrna-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-gff --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-info-annot --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-gfa --stacktrace
# ./gradlew integrate -Psource=glyma.Wm82.gnm4.ann1-pathway --stacktrace


## Lee.gnm1
# ./gradlew integrate -Psource=glyma.Lee.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-mrna-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-gff --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-info-annot --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-gfa --stacktrace
# ./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-pathway --stacktrace


## Zh13.gnm1
# ./gradlew integrate -Psource=glyma.Zh13.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-gff --stacktrace
# ./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-gfa --stacktrace
# ./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-pathway --stacktrace


## PI483463.gnm1
# ./gradlew integrate -Psource=glyso.PI483463.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-mrna-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-gff --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-info-annot --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-gfa --stacktrace
# ./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-pathway --stacktrace

## W05.gnm1
# ./gradlew integrate -Psource=glyso.W05.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.W05.gnm1.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.W05.gnm1.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=glyso.W05.gnm1.ann1-gff --stacktrace
# ./gradlew integrate -Psource=glyso.W05.gnm1.ann1-gfa --stacktrace
# ./gradlew integrate -Psource=glyso.W05.gnm1.ann1-pathway --stacktrace


## genetic maps
./gradlew integrate -Psource=glyma.mixed.map.GmComposite2003 --stacktrace

## QTLs
./gradlew integrate -Psource=glyma.mixed.qtl.GmComposite2003 --stacktrace

## GWAS
./gradlew integrate -Psource=glyma.mixed.gwas.Zhao_Teng_2017 --stacktrace

## pan-gene sets
./gradlew integrate -Psource=glysp.mixed.pan2-hsh --stacktrace
