#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}MAP${NC} ################################"
echo -e "#################################################################"

## glyma
./gradlew integrate --stacktrace -Psource=mixed.map.GmComposite1999
./gradlew integrate --stacktrace -Psource=mixed.map.GmComposite2003
./gradlew integrate --stacktrace -Psource=mixed.map.GmFeChlorosis
./gradlew integrate --stacktrace -Psource=mixed.map.GmFeChlorosis2
./gradlew integrate --stacktrace -Psource=mixed.map.GmRAPD-Sclero
./gradlew integrate --stacktrace -Psource=mixed.map.GmRAPD-SIU
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-CEW
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-CEW2
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-CEW3
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-Chiba
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-Chiba2
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-GA1996a
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-GA1996b
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-GA1998
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-JPT
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-KGL
./gradlew integrate --stacktrace -Psource=mixed.map.GmRFLP-USDAARS-RCS
./gradlew integrate --stacktrace -Psource=mixed.map.GmSCN
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-MO
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-Sclero
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-SIU
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-Utah
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-Utah2
./gradlew integrate --stacktrace -Psource=mixed.map.GmSSR-Utah3
./gradlew integrate --stacktrace -Psource=mixed.map.GmUSDA1997
./gradlew integrate --stacktrace -Psource=mixed.map.GmUtah1996
