#!/bin/sh
echo "********** soymine/integrate **********"
ant clean
#ant -v -Dsource=so,go,chado-genomics,chado-genetics,chado-featureprop,chado-go,chado-homology,chado-reactome-file,gff-geneticmarkers,file-cmap,file-qtlmarkers,soybean-expression,entrez-organism
ant -v -Dsource=gff-geneticmarkers,file-cmap,file-qtlmarkers,soybean-expression,entrez-organism
