#!/bin/sh
echo "********** soymine/integrate **********"
#ant -Dsource=go
#ant -Dsource=so
ant clean
ant -Dsource=chado-genomics
ant -Dsource=gff-geneticmarkers
ant -Dsource=chado-genetics
ant -Dsource=chado-featureprop
ant -Dsource=chado-go
ant -Dsource=file-cmap
ant -Dsource=file-qtlmarkers
ant -Dsource=entrez-organism
